language: node_js
node_js:
  - 0.12
before_install:
  - npm install -g bower
  - npm install -g gulp
before_script:
script:
  - gulp APP_DIR_CLEAR
  - gulp sass
  - gulp imagemin
  - gulp babel
  - gulp jade
  - gulp static
  - gulp browser-sync
  - gulp deploy
sudo: false
